# Generated by Django 5.2.5 on 2025-08-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Azienda')),
                ('subject', models.CharField(max_length=300, verbose_name='Oggetto')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('is_read', models.BooleanField(default=False, verbose_name='Letto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contatto',
                'verbose_name_plural': 'Contatti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='Tecnologie')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Immagine')),
                ('is_featured', models.BooleanField(default=False, verbose_name='In evidenza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Data completamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['-completed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Sottotitolo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Mumble', max_length=200, verbose_name='Titolo sito')),
                ('hero_title', models.CharField(default='Gestionale su misura.\nProcessi più fluidi.\nCrescita misurabile.', max_length=500, verbose_name='Titolo hero')),
                ('hero_subtitle', models.TextField(default='Creiamo gestionali B2B che liberano tempo e risorse.', verbose_name='Sottotitolo hero')),
                ('hero_description', models.TextField(default='Trasformiamo la complessità dei tuoi processi in percorsi chiari ed efficienti.', verbose_name='Descrizione hero')),
                ('contact_email', models.EmailField(default='info@mumble.group', max_length=254, verbose_name='Email contatto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni sito',
                'verbose_name_plural': 'Impostazioni sito',
            },
        ),
    ]
